# Generated by Django 3.2 on 2021-04-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtmospherePressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_location', models.CharField(max_length=150, verbose_name='Местонахождения датчика')),
                ('date', models.DateField(verbose_name='Дата замера')),
                ('time', models.TimeField(verbose_name='Время замера')),
                ('temperature', models.SmallIntegerField(verbose_name='Температура')),
                ('sensor_name', models.CharField(max_length=150, verbose_name='Название датчика')),
                ('sensor_model', models.CharField(max_length=150, verbose_name='Модель датчика')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
    ]
